[package]
name = "varda-daemon"
version = "0.1.0"
edition = "2024"
workspace = "../app"

[dependencies]
anyhow = { workspace = true }
bollard = { workspace = true }
bollard-stubs = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
turso = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
zenoh = { workspace = true }
